### ISSUE TITLE
Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback

### ISSUE THREAD

**Issue by jackmcconnell** [danieliser/edd-file-watermarking#1]
Steps to reproduce: 
* Install extension via WP Admin > Plugins > Add New > Upload Plugin
* Activate extension.
* Naviagation to Downloads > Settings > Extensions > Watermarking.
* Add a new Watermark of type 'Add File', 'license.txt', *blank*, {license_key}
* Click 'Save Changes'.

Fatal error then shows: 

`Fatal  error: Uncaught TypeError: call_user_func_array(): Argument #1  ($callback) must be a valid callback, function  "EDDFileWatermarking\sanitize_watermark_repeater_settings" not found or  invalid function name in /app/public/wp-includes/class-wp-hook.php on line 324`

**Comment by jackmcconnell** [comment]
Fatal error fixed in https://github.com/danieliser/edd-file-watermarking/tree/patch/1.

**Comment by danieliser** [comment]
Merging it today.
