### ISSUE TITLE
Corrupt zip file after installing edd-watermark

### ISSUE THREAD

**Issue by jackmcconnell** [danieliser/edd-file-watermarking#2]
I can't verify this yet however, here are the details: 

1. Made a duplicate of live site to run locally using Local by Flywheel. 
2. Installed EDD Watermark and activated.
3. Added the following settings: <img width="1425" alt="Screenshot 2024-02-09 at 09 42 45" src="https://github.com/danieliser/edd-file-watermarking/assets/1181188/69883f4f-6926-4dbd-9e67-826f177b2162">
4. Testing by switching to another user and downloading their purchase zip file. 
5. Attempting to open using Unarchiver or Archive Utility on macOS Sonoma (latest) results in the following error: <img width="479" alt="Screenshot 2024-02-09 at 09 44 11" src="https://github.com/danieliser/edd-file-watermarking/assets/1181188/3d6f2cbd-db80-44aa-b7e3-e428ebb49e58">
6. Doing the same thing on the live site, where EDD Watermark ins't installed, allows download and unzip of working zip file. 

Not sure if related to https://core.trac.wordpress.org/ticket/60398

**Comment by danieliser** [comment]
@jackmcconnell - I've actually seen quite a bit of this lately with WP but going the other way, taking known good zips and getting errors that they didn't contain valid plugins.

I'm gonna set up a clean test and try to replicate this particular issue this week.

**Comment by danieliser** [comment]
Haven't seen this or heard it from anyone else. Closing for now.
