### ISSUE TITLE
Fatal error when saving settings for the first time

### ISSUE THREAD

**Issue by zackkatz** [danieliser/edd-file-watermarking#4]
Installed, went to settings to create a new watermark.

Selected "Append to File", entered the file path, skipped "Search String", and set the value for the watermark.

Saving the settings resulted in:

[01-Aug-2024 13:37:57 UTC] PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "EDDFileWatermarking\sanitize_watermark_repeater_settings" not found or invalid function name in [path]/public_html/wp-includes/class-wp-hook.php:324
Stack trace:
#0 [path]/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#1 [path]/public_html/wp-content/plugins/easy-digital-downloads-pro/includes/admin/settings/register-settings.php(369): apply_filters()
#2 [path]/public_html/wp-includes/class-wp-hook.php(326): edd_settings_sanitize()
#3 [path]/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#4 [path]/public_html/wp-includes/formatting.php(5115): apply_filters()
#5 [path]/public_html/wp-includes/option.php(866): sanitize_option()
#6 [path]/public_html/wp-admin/options.php(344): update_option()
#7 {main}

**Comment by danieliser** [comment]
Should be resolved in v1.1.0 release shortly, it was patched but never merged for some reason.
